# Generated by Django 4.1.2 on 2022-10-25 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0002_alter_profile_options_delete_purchasedmovies"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("50597d21-ec4c-47f5-b0e8-fc6f85a68f85"),
            ),
        ),
    ]
