# Generated by Django 4.1.2 on 2022-10-25 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0003_profile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("1e0ca2a2-f00a-4847-8b51-0597ead50564"),
            ),
        ),
    ]
