# Generated by Django 4.1.2 on 2022-10-30 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0005_alter_profile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("e656fc4e-295a-4bfc-8468-3c1e34ccc79e"),
            ),
        ),
    ]
