services:
  billing_db:
    image: postgres:13-alpine3.16
    restart: always
    container_name: billing_db
    ports:
      - "5434:5432"
    env_file:
      - billing_db/.env

  redis:
    image: redis:6.2.6
    restart: always
    container_name: redis_billing
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
