# Generated by Django 4.1.2 on 2022-10-28 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("front_end", "0003_product_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansubscriptionmovie",
            name="device",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="plansubscriptionmovie",
            name="quality",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("0d4d1793-58d9-44bf-a5f4-9a8cdf2f5ede"),
            ),
        ),
    ]
