# Generated by Django 4.1.2 on 2022-10-30 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("front_end", "0004_plansubscriptionmovie_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plansubscriptionmovie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("8b3217f7-455b-44f6-b89d-e426c8e7a90b")
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.UUID("e36c6141-157e-43bd-b716-63ffa3a4b676"),
            ),
        ),
    ]
